parserOptions:
  sourceType: module
  ecmaVersion: 2015
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
env:
  node: true
  browser: false
rules:
  # POSSIBLE PROBLEMS
  # https://eslint.org/docs/rules/#possible-problems

  array-callback-return: error
  constructor-super: error
  for-direction: error
  getter-return: error
  no-async-promise-executor: error
  no-await-in-loop: error
  no-class-assign: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-const-assign: error
  no-constant-binary-expression: error
  no-constant-condition: error
  no-constructor-return: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-else-if: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-empty-character-class: error
  no-empty-pattern: error
  no-ex-assign: error
  no-fallthrough: error
  no-func-assign: error
  no-import-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-loss-of-precision: error
  no-misleading-character-class: error
  no-new-symbol: error
  no-obj-calls: error
  no-promise-executor-return: error
  no-prototype-builtins: error
  no-self-assign: error
  no-self-compare: error
  no-setter-return: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-this-before-super: error
  no-unexpected-multiline: error
  no-unmodified-loop-condition: error
  no-unreachable: error
  no-unreachable-loop: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  no-unsafe-optional-chaining: error
  no-unused-private-class-members: error
  no-useless-backreference: error
  require-atomic-updates: error
  use-isnan: error
  valid-typeof: error

  # TypeScript

  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      typedefs: false

  # LAYOUT & FORMATTING
  # https://eslint.org/docs/rules/#layout-formatting

  array-bracket-newline:
    - warn
    - consistent
  array-bracket-spacing:
    - warn
    - never
  array-element-newline:
    - warn
    - consistent
  arrow-parens:
    - warn
    - as-needed
  arrow-spacing:
    - warn
    - before: true
      after: true
  block-spacing:
    - warn
    - always
  brace-style:
    - warn
    - 1tbs
  comma-dangle:
    - warn
    - never
  comma-spacing:
    - warn
    - before: false
      after: true
  comma-style:
    - warn
    - last
  computed-property-spacing:
    - warn
    - never
  dot-location:
    - warn
    - property
  eol-last:
    - warn
    - always
  func-call-spacing:
    - warn
    - never
  function-call-argument-newline:
    - warn
    - consistent
  function-paren-newline:
    - warn
    - consistent
  implicit-arrow-linebreak:
    - warn
    - beside
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - warn
    - before: true
      after: true
  linebreak-style:
    - warn
    - unix
  lines-between-class-members:
    - warn
    - always
  new-parens:
    - warn
    - always
  newline-per-chained-call:
    - warn
    - ignoreChainWithDepth: 2
  no-extra-parens:
    - warn
    - all
  no-multi-spaces:
    - warn
  no-multiple-empty-lines:
    - warn
    - max: 2
  no-tabs:
    - warn
  no-trailing-spaces:
    - warn
    - skipBlankLines: false
      ignoreComments: true
  no-whitespace-before-property:
    - warn
  nonblock-statement-body-position:
    - warn
    - beside
  object-curly-newline:
    - warn
    - consistent: true
  object-curly-spacing:
    - warn
    - always
  object-property-newline:
    - warn
  operator-linebreak:
    - warn
  padded-blocks:
    - warn
    - never
  padding-line-between-statements:
    - warn
  quotes:
    - warn
    - single
  rest-spread-spacing:
    - warn
    - never
  semi:
    - warn
    - never
  semi-spacing:
    - warn
    - before: false
      after: true
  semi-style:
    - warn
    - last
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - anonymous: always
      named: never
      asyncArrow: always
  space-in-parens:
    - warn
    - never
  space-infix-ops:
    - warn
  space-unary-ops:
    - warn
    - words: true
      nonwords: false
  switch-colon-spacing:
    - warn
    - after: true
      before: false
  template-curly-spacing:
    - warn
    - never
  template-tag-spacing:
    - warn
    - never
  unicode-bom:
    - warn
    - never
